### PR TITLE
add scoop support

### PR DESCRIPTION
**Pull request by Deliganli**
scoop allows windows users to install programs from console, apt-like usage.

I use scoop to install my programs, windows terminal is included. Maybe this configuration can be tweaked better, tried to kickstart.

Also it would be a good idea to apply for main or extras bucket of scoop to appear on searches

Currently how to install with scoop is like below;
`scoop install https://github.com/Deliganli/windows-terminal-quake/blob/master/scoop/windows-terminal-quake.json`

If merged;
`scoop install https://github.com/flyingpie/windows-terminal-quake/blob/master/scoop/windows-terminal-quake.json`

If accepted into main or extras bucket;
`scoop install windows-terminal-quake`

### CODE REVIEW

**Comment by flyingpie** [comment]
@Deliganli Comes along with the next release, thank you!

**Comment by Deliganli** [comment]
my pleasure, no need to release though, json file existing in master is enough, however on each release version number needs to be updated on that manifest file, along with the hash.

also to let you know, I suggested this program to be added to the `scoop-extras` bucket but it was rejected, link below
https://github.com/lukesampson/scoop-extras/pull/5400

I will open a PR for updating readme regarding the new installation method

**Comment by flyingpie** [comment]
@Deliganli Thank you. Can you provide a quick command or link to how to generate the hash?

**Comment by Deliganli** [comment]
```certUtil -hashfile windows-terminal-quake-v0.11-2020-11-02_0001.zip SHA256```

**Comment by rmobis** [comment]
For some reason I had to use the link to the raw file for scoop to work.

```bash
$ scoop install https://raw.githubusercontent.com/flyingpie/windows-terminal-quake/master/scoop/windows-terminal-quake.json
```

Also, we should probably add this to the README?

**Comment by Deliganli** [comment]
I believe raw url has been added couple weeks ago in master branch

**Pull request merged**
